import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import io

# Earthquake data
earthquakes = [
    {"lat": -46.6443, "lng": 165.4903, "mag": 5.3, "place": "New Zealand"},
    {"lat": 51.8844, "lng": -176.4897, "mag": 5.1, "place": "Alaska"},
    {"lat": -6.5908, "lng": 151.0788, "mag": 4.9, "place": "Papua New Guinea"},
    {"lat": -57.5469, "lng": -25.1411, "mag": 4.8, "place": "S. Sandwich Is."},
    {"lat": -23.5977, "lng": 179.9337, "mag": 4.7, "place": "Fiji"},
    {"lat": 37.8121, "lng": 71.9641, "mag": 4.6, "place": "Tajikistan"},
    {"lat": 51.8537, "lng": 158.5676, "mag": 4.5, "place": "Russia"},
    {"lat": -24.1919, "lng": -67.2778, "mag": 4.5, "place": "Argentina"},
]

# Create figure with dark theme
plt.style.use('dark_background')
fig, ax = plt.subplots(figsize=(14, 8), facecolor='#1a1a2e')
ax.set_facecolor('#16213e')

# Draw simple world map outline
from matplotlib.patches import Rectangle

# Simplified continents as rectangles (approximate)
ax.add_patch(Rectangle((-125, 25), 60, 30, fill=True, color='#2d3436', alpha=0.5))  # North America
ax.add_patch(Rectangle((-80, -55), 45, 60, fill=True, color='#2d3436', alpha=0.5))  # South America
ax.add_patch(Rectangle((-20, 35), 55, 35, fill=True, color='#2d3436', alpha=0.5))   # Europe
ax.add_patch(Rectangle((-20, -35), 60, 45, fill=True, color='#2d3436', alpha=0.5))  # Africa
ax.add_patch(Rectangle((60, 5), 80, 50, fill=True, color='#2d3436', alpha=0.5))     # Asia
ax.add_patch(Rectangle((110, -45), 50, 35, fill=True, color='#2d3436', alpha=0.5))  # Australia

# Grid lines
for lng in range(-180, 181, 30):
    ax.axvline(x=lng, color='#4a4a6a', linewidth=0.3, alpha=0.5)
for lat in range(-90, 91, 30):
    ax.axhline(y=lat, color='#4a4a6a', linewidth=0.3, alpha=0.5)

# Color function
def get_color(mag):
    if mag >= 5.0: return '#e74c3c'
    if mag >= 4.8: return '#e67e22'
    if mag >= 4.6: return '#f1c40f'
    return '#2ecc71'

# Size function
def get_size(mag):
    return (mag - 3) ** 3 * 30

# Plot earthquakes
for eq in earthquakes:
    color = get_color(eq['mag'])
    size = get_size(eq['mag'])
    
    # Outer glow
    ax.scatter(eq['lng'], eq['lat'], s=size*2, c=color, alpha=0.3, edgecolors='none')
    # Main dot
    ax.scatter(eq['lng'], eq['lat'], s=size, c=color, alpha=0.9, edgecolors='white', linewidths=1.5, zorder=5)
    # Label
    ax.annotate(f"M{eq['mag']}", (eq['lng'], eq['lat']), 
                xytext=(8, 8), textcoords='offset points',
                fontsize=9, color='white', fontweight='bold',
                bbox=dict(boxstyle='round,pad=0.3', facecolor=color, alpha=0.8, edgecolor='none'))

# Title
ax.set_title('🌏 Global Earthquake Map - Feb 2, 2026\nMagnitude 4.5+ Events (Past 24 Hours)', 
             fontsize=16, fontweight='bold', color='white', pad=20)

# Axis settings
ax.set_xlim(-180, 180)
ax.set_ylim(-90, 90)
ax.set_xlabel('Longitude', fontsize=10, color='#888')
ax.set_ylabel('Latitude', fontsize=10, color='#888')
ax.tick_params(colors='#888')

# Legend
legend_elements = [
    plt.scatter([], [], s=150, c='#e74c3c', label='M 5.0+', edgecolors='white', linewidths=1),
    plt.scatter([], [], s=100, c='#e67e22', label='M 4.8-4.9', edgecolors='white', linewidths=1),
    plt.scatter([], [], s=70, c='#f1c40f', label='M 4.6-4.7', edgecolors='white', linewidths=1),
    plt.scatter([], [], s=50, c='#2ecc71', label='M 4.5', edgecolors='white', linewidths=1),
]
ax.legend(handles=legend_elements, loc='lower left', fontsize=9, 
          facecolor='#1a1a2e', edgecolor='#4a4a6a', labelcolor='white')

# Footer
fig.text(0.5, 0.02, 'Data: USGS Earthquake Hazards Program | Generated by 地動先知', 
         ha='center', fontsize=9, color='#666')

plt.tight_layout()
plt.savefig('/home/node/.openclaw/workspace/earthquake_map.png', dpi=150, 
            facecolor='#1a1a2e', edgecolor='none', bbox_inches='tight')
print("Map saved successfully!")
